#include<stdio.h>
int main()
{
    int n,i,j,x,q=0;
    scanf("%d",&n);
    if(n%2==1)
    {
        x=((n+q)/2);
    }
    else
    {
        n--;
        q++;
        x=(((n+q)/2)-1);
    }
    for(i=0;i<(n+q)/2;i++)
    {
        for(j=0;j<n;j++)
        {
            if(j==(n/2)-i||j==(n/2)+i)
            {
                printf("*");
            }
            else
            {
                printf("_");
            }
        }
        printf("\n");
    }
    for(i=0;i<=x;i++)
    {
        for(j=0;j<n;j++)
        {
            if(j==i || j==((n-1)-i))
               {
                   printf("*");
               }
               else
                {
                    printf("_");
                }
        }
        printf("\n");
    }
}
